{
 "title": "Idun workers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alloc bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Sys Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_sys_bytes" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" },
    {}
   ]
  }
 ]
}